create table if not exists public.level_analysis_applications (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  exam_group text not null,
  level text not null,
  full_name text not null,
  education_status text not null,
  target_exam text not null,
  contact_info text not null,
  assessment_id bigint,
  submission_id bigint,
  status text not null default 'submitted' check (status in ('draft', 'submitted', 'reviewed')),
  created_at timestamptz not null default now()
);

create table if not exists public.level_analysis_files (
  id bigint generated by default as identity primary key,
  application_id bigint not null references public.level_analysis_applications(id) on delete cascade,
  file_path text not null,
  file_name text not null,
  mime_type text not null,
  file_size integer not null check (file_size > 0 and file_size <= 8388608),
  sort_order integer not null check (sort_order between 1 and 3),
  created_at timestamptz not null default now(),
  unique (application_id, sort_order)
);

alter table public.level_analysis_applications add column if not exists assessment_id bigint;
alter table public.level_analysis_applications add column if not exists submission_id bigint;

alter table public.level_analysis_applications enable row level security;
alter table public.level_analysis_files enable row level security;

drop policy if exists "students create their own level applications" on public.level_analysis_applications;
drop policy if exists "students read their own level applications" on public.level_analysis_applications;
drop policy if exists "students create files for their applications" on public.level_analysis_files;
drop policy if exists "students read files for their applications" on public.level_analysis_files;
drop policy if exists "students upload own level analysis files" on storage.objects;
drop policy if exists "students read own level analysis files" on storage.objects;

create policy "students create their own level applications"
  on public.level_analysis_applications for insert
  with check (auth.uid() = user_id);

create policy "students read their own level applications"
  on public.level_analysis_applications for select
  using (auth.uid() = user_id);

drop policy if exists "admins manage all level applications" on public.level_analysis_applications;
create policy "admins manage all level applications"
  on public.level_analysis_applications for all to authenticated using (exists (
    select 1 from public.profiles p where p.id = auth.uid() and p.role = 'admin'
  )) with check (exists (
    select 1 from public.profiles p where p.id = auth.uid() and p.role = 'admin'
  ));

drop policy if exists "admins read all level analysis files" on public.level_analysis_files;
create policy "admins read all level analysis files"
  on public.level_analysis_files for select to authenticated using (exists (
    select 1 from public.profiles p where p.id = auth.uid() and p.role = 'admin'
  ));

create policy "students create files for their applications"
  on public.level_analysis_files for insert
  with check (exists (
    select 1 from public.level_analysis_applications a
    where a.id = application_id and a.user_id = auth.uid()
  ));

create policy "students read files for their applications"
  on public.level_analysis_files for select
  using (exists (
    select 1 from public.level_analysis_applications a
    where a.id = application_id and a.user_id = auth.uid()
  ));

insert into storage.buckets (id, name, public)
values ('level-analysis-solutions', 'level-analysis-solutions', false)
on conflict (id) do nothing;

create policy "students upload own level analysis files"
  on storage.objects for insert to authenticated
  with check (bucket_id = 'level-analysis-solutions' and (storage.foldername(name))[1] = auth.uid()::text);

create policy "students read own level analysis files"
  on storage.objects for select to authenticated
  using (bucket_id = 'level-analysis-solutions' and (storage.foldername(name))[1] = auth.uid()::text);

-- Additive assessment model.
-- The existing `submissions` table belongs to Haftanin Problemi and is not reused.
-- `profiles` is the existing student identity table; a separate students table is unnecessary.

create table if not exists public.assessment_categories (
  id bigint generated by default as identity primary key,
  slug text not null unique,
  name text not null unique,
  description text,
  is_active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.assessment_levels (
  id bigint generated by default as identity primary key,
  category_id bigint not null references public.assessment_categories(id) on delete cascade,
  slug text not null,
  name text not null,
  sort_order integer not null default 0,
  is_active boolean not null default true,
  unique (category_id, slug)
);

create table if not exists public.assessments (
  id bigint generated by default as identity primary key,
  category_id bigint not null references public.assessment_categories(id),
  level_id bigint not null references public.assessment_levels(id),
  title text not null,
  description text,
  duration_minutes integer not null default 45 check (duration_minutes > 0),
  question_count integer not null default 0 check (question_count >= 0),
  pdf_path text,
  status text not null default 'draft' check (status in ('draft', 'published', 'archived')),
  created_by uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.assessment_questions (
  id bigint generated by default as identity primary key,
  assessment_id bigint not null references public.assessments(id) on delete cascade,
  question_number integer not null check (question_number > 0),
  question_text text,
  question_ref text,
  topic text not null,
  subtopic text,
  difficulty text not null default 'medium' check (difficulty in ('easy', 'medium', 'hard')),
  correct_answer text,
  points numeric(6,2) not null default 1 check (points > 0),
  unique (assessment_id, question_number),
  check (question_text is not null or question_ref is not null)
);

create table if not exists public.assessment_submissions (
  id bigint generated by default as identity primary key,
  student_id uuid not null references public.profiles(id) on delete cascade,
  assessment_id bigint not null references public.assessments(id),
  status text not null default 'pending' check (status in ('pending', 'reviewing', 'completed')),
  created_at timestamptz not null default now(),
  reviewed_at timestamptz,
  reviewed_by uuid references public.profiles(id) on delete set null
);

create table if not exists public.assessment_submission_files (
  id bigint generated by default as identity primary key,
  submission_id bigint not null references public.assessment_submissions(id) on delete cascade,
  storage_path text not null,
  file_name text not null,
  mime_type text not null,
  file_size integer not null check (file_size > 0 and file_size <= 8388608),
  sort_order integer not null check (sort_order between 1 and 3),
  created_at timestamptz not null default now(),
  unique (submission_id, sort_order)
);

create table if not exists public.assessment_question_results (
  id bigint generated by default as identity primary key,
  submission_id bigint not null references public.assessment_submissions(id) on delete cascade,
  question_id bigint not null references public.assessment_questions(id) on delete cascade,
  result text not null check (result in ('correct', 'wrong', 'blank')),
  error_type text check (error_type in ('concept_error', 'calculation_error', 'method_error', 'careless_error')),
  teacher_note text,
  points_earned numeric(6,2) not null default 0 check (points_earned >= 0),
  reviewed_by uuid references public.profiles(id) on delete set null,
  reviewed_at timestamptz,
  unique (submission_id, question_id)
);

create table if not exists public.assessment_topic_results (
  id bigint generated by default as identity primary key,
  submission_id bigint not null references public.assessment_submissions(id) on delete cascade,
  topic text not null,
  question_count integer not null default 0 check (question_count >= 0),
  correct_count integer not null default 0 check (correct_count >= 0),
  wrong_count integer not null default 0 check (wrong_count >= 0),
  blank_count integer not null default 0 check (blank_count >= 0),
  points_earned numeric(8,2) not null default 0 check (points_earned >= 0),
  unique (submission_id, topic)
);

create table if not exists public.assessment_reports (
  id bigint generated by default as identity primary key,
  submission_id bigint not null unique references public.assessment_submissions(id) on delete cascade,
  overall_score numeric(8,2),
  level_label text,
  strengths jsonb not null default '[]'::jsonb,
  weaknesses jsonb not null default '[]'::jsonb,
  recommendations jsonb not null default '[]'::jsonb,
  generated_by text not null default 'teacher' check (generated_by in ('teacher', 'system', 'ai')),
  report_text text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

do $$
begin
  if not exists (select 1 from pg_constraint where conname = 'level_analysis_applications_assessment_id_fkey') then
    alter table public.level_analysis_applications
      add constraint level_analysis_applications_assessment_id_fkey
      foreign key (assessment_id) references public.assessments(id) on delete set null;
  end if;
  if not exists (select 1 from pg_constraint where conname = 'level_analysis_applications_submission_id_fkey') then
    alter table public.level_analysis_applications
      add constraint level_analysis_applications_submission_id_fkey
      foreign key (submission_id) references public.assessment_submissions(id) on delete set null;
  end if;
end $$;

create index if not exists assessment_levels_category_idx on public.assessment_levels (category_id, sort_order);
create index if not exists assessments_catalog_idx on public.assessments (category_id, level_id, status);
create index if not exists assessment_questions_assessment_idx on public.assessment_questions (assessment_id, question_number);
create index if not exists assessment_submissions_student_idx on public.assessment_submissions (student_id, created_at desc);
create index if not exists assessment_submissions_status_idx on public.assessment_submissions (status, created_at desc);
create index if not exists assessment_question_results_submission_idx on public.assessment_question_results (submission_id);
create index if not exists assessment_topic_results_submission_idx on public.assessment_topic_results (submission_id);

alter table public.assessment_categories enable row level security;
alter table public.assessment_levels enable row level security;
alter table public.assessments enable row level security;
alter table public.assessment_questions enable row level security;
alter table public.assessment_submissions enable row level security;
alter table public.assessment_submission_files enable row level security;
alter table public.assessment_question_results enable row level security;
alter table public.assessment_topic_results enable row level security;
alter table public.assessment_reports enable row level security;

drop policy if exists "authenticated users read active assessment categories" on public.assessment_categories;
drop policy if exists "authenticated users read active assessment levels" on public.assessment_levels;
drop policy if exists "authenticated users read published assessments" on public.assessments;
drop policy if exists "authenticated users read published assessment questions" on public.assessment_questions;
drop policy if exists "students create own assessment submissions" on public.assessment_submissions;
drop policy if exists "students read own assessment submissions" on public.assessment_submissions;
drop policy if exists "students create own submission files" on public.assessment_submission_files;
drop policy if exists "students read own submission files" on public.assessment_submission_files;
drop policy if exists "admins manage submission files" on public.assessment_submission_files;
drop policy if exists "students read own question results" on public.assessment_question_results;
drop policy if exists "students read own topic results" on public.assessment_topic_results;
drop policy if exists "students read own assessment reports" on public.assessment_reports;
drop policy if exists "admins manage assessment catalog" on public.assessment_categories;
drop policy if exists "admins manage assessment levels" on public.assessment_levels;
drop policy if exists "admins manage assessments" on public.assessments;
drop policy if exists "admins manage assessment questions" on public.assessment_questions;
drop policy if exists "admins review assessment submissions" on public.assessment_submissions;
drop policy if exists "admins manage assessment results" on public.assessment_question_results;
drop policy if exists "admins manage topic results" on public.assessment_topic_results;
drop policy if exists "admins manage assessment reports" on public.assessment_reports;
drop policy if exists "admins read all assessment solution files" on storage.objects;

create policy "authenticated users read active assessment categories"
  on public.assessment_categories for select to authenticated using (is_active);

create policy "authenticated users read active assessment levels"
  on public.assessment_levels for select to authenticated using (is_active);

create policy "authenticated users read published assessments"
  on public.assessments for select to authenticated using (status = 'published');

create policy "authenticated users read published assessment questions"
  on public.assessment_questions for select to authenticated using (exists (
    select 1 from public.assessments a
    where a.id = assessment_id and a.status = 'published'
  ));

create policy "students create own assessment submissions"
  on public.assessment_submissions for insert to authenticated
  with check (auth.uid() = student_id and exists (
    select 1 from public.assessments a where a.id = assessment_id and a.status = 'published'
  ));

create policy "students read own assessment submissions"
  on public.assessment_submissions for select to authenticated
  using (auth.uid() = student_id);

create policy "students create own submission files"
  on public.assessment_submission_files for insert to authenticated
  with check (storage_path like auth.uid()::text || '/%' and exists (
    select 1 from public.assessment_submissions s
    where s.id = submission_id and s.student_id = auth.uid()
  ));

create policy "students read own submission files"
  on public.assessment_submission_files for select to authenticated
  using (exists (
    select 1 from public.assessment_submissions s
    where s.id = submission_id and s.student_id = auth.uid()
  ));

create policy "admins manage submission files"
  on public.assessment_submission_files for all to authenticated using (exists (
    select 1 from public.profiles p where p.id = auth.uid() and p.role = 'admin'
  )) with check (exists (
    select 1 from public.profiles p where p.id = auth.uid() and p.role = 'admin'
  ));

create policy "students read own question results"
  on public.assessment_question_results for select to authenticated
  using (exists (
    select 1 from public.assessment_submissions s
    where s.id = submission_id and s.student_id = auth.uid()
  ));

create policy "students read own topic results"
  on public.assessment_topic_results for select to authenticated
  using (exists (
    select 1 from public.assessment_submissions s
    where s.id = submission_id and s.student_id = auth.uid()
  ));

create policy "students read own assessment reports"
  on public.assessment_reports for select to authenticated
  using (exists (
    select 1 from public.assessment_submissions s
    where s.id = submission_id and s.student_id = auth.uid()
  ));

-- Existing authorization has `admin`, not `teacher`; admin is the current reviewer role.
create policy "admins manage assessment catalog"
  on public.assessment_categories for all to authenticated using (exists (
    select 1 from public.profiles p where p.id = auth.uid() and p.role = 'admin'
  )) with check (exists (
    select 1 from public.profiles p where p.id = auth.uid() and p.role = 'admin'
  ));

create policy "admins manage assessment levels"
  on public.assessment_levels for all to authenticated using (exists (
    select 1 from public.profiles p where p.id = auth.uid() and p.role = 'admin'
  )) with check (exists (
    select 1 from public.profiles p where p.id = auth.uid() and p.role = 'admin'
  ));

create policy "admins manage assessments"
  on public.assessments for all to authenticated using (exists (
    select 1 from public.profiles p where p.id = auth.uid() and p.role = 'admin'
  )) with check (exists (
    select 1 from public.profiles p where p.id = auth.uid() and p.role = 'admin'
  ));

create policy "admins manage assessment questions"
  on public.assessment_questions for all to authenticated using (exists (
    select 1 from public.profiles p where p.id = auth.uid() and p.role = 'admin'
  )) with check (exists (
    select 1 from public.profiles p where p.id = auth.uid() and p.role = 'admin'
  ));

create policy "admins review assessment submissions"
  on public.assessment_submissions for all to authenticated using (exists (
    select 1 from public.profiles p where p.id = auth.uid() and p.role = 'admin'
  )) with check (exists (
    select 1 from public.profiles p where p.id = auth.uid() and p.role = 'admin'
  ));

create policy "admins manage assessment results"
  on public.assessment_question_results for all to authenticated using (exists (
    select 1 from public.profiles p where p.id = auth.uid() and p.role = 'admin'
  )) with check (exists (
    select 1 from public.profiles p where p.id = auth.uid() and p.role = 'admin'
  ));

create policy "admins manage topic results"
  on public.assessment_topic_results for all to authenticated using (exists (
    select 1 from public.profiles p where p.id = auth.uid() and p.role = 'admin'
  )) with check (exists (
    select 1 from public.profiles p where p.id = auth.uid() and p.role = 'admin'
  ));

create policy "admins manage assessment reports"
  on public.assessment_reports for all to authenticated using (exists (
    select 1 from public.profiles p where p.id = auth.uid() and p.role = 'admin'
  )) with check (exists (
    select 1 from public.profiles p where p.id = auth.uid() and p.role = 'admin'
  ));

create policy "admins read all assessment solution files"
  on storage.objects for select to authenticated
  using (bucket_id = 'level-analysis-solutions' and exists (
    select 1 from public.profiles p where p.id = auth.uid() and p.role = 'admin'
  ));

insert into public.assessment_categories (slug, name, description) values
  ('tyt-ayt', 'TYT / AYT', 'YKS''ye hazırlanan öğrenciler için'),
  ('ortaokul', 'Ortaokul', '5, 6, 7 ve 8. sınıf öğrencileri için'),
  ('kpss', 'KPSS', 'KPSS''ye hazırlanan adaylar için'),
  ('ales', 'ALES', 'ALES''e hazırlanan adaylar için'),
  ('dgs', 'DGS', 'DGS''ye hazırlanan adaylar için'),
  ('diger', 'Diğer', 'Diğer matematik seviyeleri')
on conflict (slug) do nothing;

insert into public.assessment_levels (category_id, slug, name, sort_order)
select c.id, v.slug, v.name, v.sort_order
from public.assessment_categories c
join (values
  ('tyt-ayt', 'tyt-matematik', 'TYT Matematik', 1),
  ('tyt-ayt', 'ayt-matematik', 'AYT Matematik', 2),
  ('tyt-ayt', 'tyt-ayt', 'TYT + AYT', 3),
  ('ortaokul', '5-sinif', '5. Sınıf', 1),
  ('ortaokul', '6-sinif', '6. Sınıf', 2),
  ('ortaokul', '7-sinif', '7. Sınıf', 3),
  ('ortaokul', '8-sinif', '8. Sınıf', 4),
  ('ortaokul', 'lgs', 'LGS', 5),
  ('kpss', 'kpss-matematik', 'KPSS Matematik', 1),
  ('ales', 'ales-sayisal', 'ALES Sayısal', 1),
  ('dgs', 'dgs-sayisal', 'DGS Sayısal', 1),
  ('diger', 'diger', 'Diğer Matematik', 1)
) as v(category_slug, slug, name, sort_order) on v.category_slug = c.slug
on conflict (category_id, slug) do nothing;

insert into public.assessments (category_id, level_id, title, description, duration_minutes, question_count, status)
select l.category_id, l.id, l.name || ' Seviye Testi 1', 'Matematik seviyeni konu bazında görmek için örnek değerlendirme.',
  case when l.name in ('TYT Matematik', 'AYT Matematik', 'TYT + AYT') then 45 else 30 end,
  case when l.name in ('TYT Matematik', 'AYT Matematik', 'TYT + AYT') then 20 else 15 end,
  'published'
from public.assessment_levels l
where not exists (
  select 1 from public.assessments existing
  where existing.category_id = l.category_id
    and existing.level_id = l.id
    and existing.title = l.name || ' Seviye Testi 1'
);

insert into public.assessment_questions (assessment_id, question_number, question_text, topic, subtopic, difficulty, correct_answer, points)
select a.id, q.question_number, q.question_text, q.topic, q.subtopic, q.difficulty, q.correct_answer, 1
from public.assessments a
cross join (values
  (1, 'Birinci örnek soru: 2x + 4 = 10 denkleminde x kaçtır?', 'Temel İşlemler', 'Denklemler', 'easy', '3'),
  (2, 'İkinci örnek soru: f(x) = x + 2 ise f(3) kaçtır?', 'Fonksiyonlar', 'Fonksiyon Değeri', 'medium', '5'),
  (3, 'Üçüncü örnek soru: Bir üçgenin iç açıları toplamı kaç derecedir?', 'Geometri', 'Üçgenler', 'easy', '180')
) as q(question_number, question_text, topic, subtopic, difficulty, correct_answer)
where a.status = 'published'
on conflict (assessment_id, question_number) do nothing;