-- ============================================================================
-- Supabase migration: Guncel Bilgiler Modulu
-- Dosya: orhanakyavuz-v4/backend/db/supabase-current-info.sql
-- ============================================================================

-- 1. Tablo: content_sources (Resmi Kaynak Tanimlari)
create table if not exists public.content_sources (
  id bigint generated by default as identity primary key,
  name text not null,
  slug text not null unique,
  website_url text not null,
  feed_url text,
  category text not null check (category in ('banka', 'kamu', 'sinav', 'egitim', 'diger')),
  source_type text not null default 'scraper' check (source_type in ('rss', 'api', 'scraper', 'manual')),
  is_active boolean not null default true,
  last_checked_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- 2. Tablo: current_updates (Guncel Duyurular, Ilanlar ve Sinav Bilgileri)
create table if not exists public.current_updates (
  id bigint generated by default as identity primary key,
  source_id bigint not null references public.content_sources(id) on delete cascade,
  title text not null,
  summary text,
  original_url text not null,
  category text not null check (category in ('banka', 'kamu', 'ags', 'kpss', 'ales', 'dgs', 'egitim', 'diger')),
  publish_date timestamptz not null default now(),
  fetched_at timestamptz not null default now(),
  status text not null default 'published' check (status in ('draft', 'published', 'archived')),
  external_id text,
  dedup_hash text not null unique,
  is_featured boolean not null default false,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- 3. Performans ve Arama Indeksleri
create index if not exists idx_current_sources_category_active
  on public.content_sources (category, is_active);

create index if not exists idx_current_updates_feed
  on public.current_updates (status, publish_date desc, is_featured desc);

create index if not exists idx_current_updates_category_feed
  on public.current_updates (category, status, publish_date desc);

create index if not exists idx_current_updates_source_id
  on public.current_updates (source_id);

-- 4. Row Level Security (RLS) Etkinlestirme
alter table public.content_sources enable row level security;
alter table public.current_updates enable row level security;

-- 5. RLS Politikalari: content_sources
drop policy if exists "active sources are public" on public.content_sources;
create policy "active sources are public"
  on public.content_sources for select
  using (is_active = true);

drop policy if exists "admins manage content sources" on public.content_sources;
create policy "admins manage content sources"
  on public.content_sources for all
  to authenticated
  using (
    exists (
      select 1 from public.profiles p
      where p.id = auth.uid() and p.role = 'admin'
    )
  )
  with check (
    exists (
      select 1 from public.profiles p
      where p.id = auth.uid() and p.role = 'admin'
    )
  );

-- 6. RLS Politikalari: current_updates
drop policy if exists "published updates are public" on public.current_updates;
create policy "published updates are public"
  on public.current_updates for select
  using (status = 'published');

drop policy if exists "admins manage current updates" on public.current_updates;
create policy "admins manage current updates"
  on public.current_updates for all
  to authenticated
  using (
    exists (
      select 1 from public.profiles p
      where p.id = auth.uid() and p.role = 'admin'
    )
  )
  with check (
    exists (
      select 1 from public.profiles p
      where p.id = auth.uid() and p.role = 'admin'
    )
  );
