-- Supabase/PostgreSQL migration for Haftanin Problemi.
-- Run this in the Supabase SQL editor before setting AUTH_PROVIDER=supabase.

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  display_name text not null default 'Matematikci',
  role text not null default 'student' check (role in ('student', 'admin')),
  created_at timestamptz not null default now()
);

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = public
as $$
begin
  insert into public.profiles (id, display_name)
  values (new.id, coalesce(new.raw_user_meta_data ->> 'display_name', 'Matematikci'))
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

create table if not exists public.weekly_problems (
  id bigint generated by default as identity primary key,
  slug text not null unique,
  title text not null,
  problem_content text not null,
  solution_content text,
  topic text not null,
  grade_level text not null,
  difficulty text not null check (difficulty in ('easy', 'medium', 'hard')),
  answer_key text not null,
  published_at timestamptz not null,
  ends_at timestamptz not null,
  status text not null default 'draft' check (status in ('draft', 'published', 'archived')),
  created_by uuid references public.profiles(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.submissions (
  id bigint generated by default as identity primary key,
  problem_id bigint not null references public.weekly_problems(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  answer_text text not null,
  solution_text text,
  is_correct boolean not null default false,
  has_explanation boolean not null default false,
  score integer not null default 0 check (score >= 0),
  submitted_at timestamptz not null default now()
);

create table if not exists public.score_events (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  submission_id bigint references public.submissions(id) on delete set null,
  event_type text not null,
  points integer not null,
  created_at timestamptz not null default now()
);

create table if not exists public.streaks (
  user_id uuid primary key references public.profiles(id) on delete cascade,
  current_streak integer not null default 0,
  longest_streak integer not null default 0,
  last_participation_week date,
  updated_at timestamptz not null default now()
);

create table if not exists public.badges (
  id bigint generated by default as identity primary key,
  code text not null unique,
  name text not null,
  description text not null,
  icon text not null,
  criteria_type text not null,
  criteria_value integer not null,
  is_active boolean not null default true
);

create table if not exists public.user_badges (
  user_id uuid not null references public.profiles(id) on delete cascade,
  badge_id bigint not null references public.badges(id) on delete cascade,
  earned_at timestamptz not null default now(),
  primary key (user_id, badge_id)
);

create table if not exists public.problem_highlights (
  id bigint generated by default as identity primary key,
  problem_id bigint not null references public.weekly_problems(id) on delete cascade,
  submission_id bigint not null unique references public.submissions(id) on delete cascade,
  highlight_type text not null default 'weekly_solution',
  approved_by uuid not null references public.profiles(id),
  approved_at timestamptz not null default now()
);

create index if not exists weekly_problems_archive_idx
  on public.weekly_problems (published_at desc, topic, difficulty);
create index if not exists submissions_problem_user_idx
  on public.submissions (problem_id, user_id);
create index if not exists score_events_user_idx
  on public.score_events (user_id, created_at desc);

alter table public.profiles enable row level security;
alter table public.weekly_problems enable row level security;
alter table public.submissions enable row level security;
alter table public.score_events enable row level security;
alter table public.streaks enable row level security;
alter table public.badges enable row level security;
alter table public.user_badges enable row level security;
alter table public.problem_highlights enable row level security;

create policy "users read their own profile"
  on public.profiles for select
  using (auth.uid() = id);

create policy "published problems are public"
  on public.weekly_problems for select
  using (status in ('published', 'archived'));

create policy "users read their own submissions"
  on public.submissions for select
  using (auth.uid() = user_id);

create policy "users create their own submissions"
  on public.submissions for insert
  with check (auth.uid() = user_id);

create policy "users read their own progress"
  on public.streaks for select
  using (auth.uid() = user_id);

create policy "users read their own badges"
  on public.user_badges for select
  using (auth.uid() = user_id);

create policy "public can read active highlights"
  on public.problem_highlights for select
  using (exists (
    select 1 from public.weekly_problems p
    where p.id = problem_id and p.status in ('published', 'archived')
  ));

create or replace function public.submit_weekly_problem(
  p_problem_id bigint,
  p_answer text,
  p_solution text default null
)
returns table (submission_id bigint, is_correct boolean, score integer)
language plpgsql
security definer set search_path = public
as $$
declare
  problem_row public.weekly_problems%rowtype;
  correct boolean;
  awarded integer;
  new_submission_id bigint;
  current_week date := date_trunc('week', now())::date;
  previous_week date := date_trunc('week', now())::date - 7;
  old_streak public.streaks%rowtype;
  next_streak integer;
  total_score integer;
begin
  if auth.uid() is null then
    raise exception using errcode = '28000', message = 'Authentication required';
  end if;

  select * into problem_row
  from public.weekly_problems
  where id = p_problem_id
    and status = 'published'
    and published_at <= now()
    and ends_at > now();

  if not found then
    raise exception using errcode = '22023', message = 'Active problem not found';
  end if;

  correct := lower(trim(coalesce(p_answer, ''))) = lower(trim(problem_row.answer_key));
  awarded := case when correct and not exists (
    select 1 from public.submissions
    where problem_id = p_problem_id and user_id = auth.uid() and is_correct
  ) then case when length(trim(coalesce(p_solution, ''))) > 0 then 15 else 10 end else 0 end;

  insert into public.submissions (problem_id, user_id, answer_text, solution_text, is_correct, has_explanation, score)
  values (p_problem_id, auth.uid(), trim(p_answer), nullif(trim(p_solution), ''), correct, length(trim(coalesce(p_solution, ''))) > 0, awarded)
  returning id into new_submission_id;

  if awarded > 0 then
    insert into public.score_events (user_id, submission_id, event_type, points)
    values (auth.uid(), new_submission_id, case when p_solution is null or trim(p_solution) = '' then 'correct_answer' else 'correct_with_explanation' end, awarded);
  end if;

  select * into old_streak from public.streaks where user_id = auth.uid();
  if old_streak.last_participation_week = current_week then
    next_streak := old_streak.current_streak;
  elsif old_streak.last_participation_week = previous_week then
    next_streak := old_streak.current_streak + 1;
  else
    next_streak := 1;
  end if;
  insert into public.streaks (user_id, current_streak, longest_streak, last_participation_week)
  values (auth.uid(), next_streak, greatest(coalesce(old_streak.longest_streak, 0), next_streak), current_week)
  on conflict (user_id) do update set current_streak = excluded.current_streak,
    longest_streak = excluded.longest_streak, last_participation_week = excluded.last_participation_week,
    updated_at = now();

  select coalesce(sum(points), 0) into total_score from public.score_events where user_id = auth.uid();
  insert into public.user_badges (user_id, badge_id)
  select auth.uid(), b.id from public.badges b
  where b.is_active and ((b.criteria_type = 'streak' and next_streak >= b.criteria_value)
    or (b.criteria_type = 'score' and total_score >= b.criteria_value))
  on conflict (user_id, badge_id) do nothing;

  return query select new_submission_id, correct, awarded;
end;
$$;

revoke all on function public.submit_weekly_problem(bigint, text, text) from public;
grant execute on function public.submit_weekly_problem(bigint, text, text) to authenticated;

create or replace function public.get_weekly_leaderboard()
returns table (name text, score bigint, solved_count bigint)
language sql
security definer set search_path = public
as $$
  select coalesce(p.display_name, 'Matematikci') as name,
    coalesce(sum(se.points), 0)::bigint as score,
    count(distinct se.submission_id)::bigint as solved_count
  from public.score_events se
  join public.profiles p on p.id = se.user_id
  group by p.id, p.display_name
  order by score desc, solved_count desc
  limit 10;
$$;

revoke all on function public.get_weekly_leaderboard() from public;
grant execute on function public.get_weekly_leaderboard() to anon, authenticated;

create or replace function public.assert_admin()
returns void
language plpgsql
security definer set search_path = public
as $$
begin
  if auth.uid() is null or not exists (
    select 1 from public.profiles where id = auth.uid() and role = 'admin'
  ) then
    raise exception using errcode = '42501', message = 'Admin role required';
  end if;
end;
$$;

create or replace function public.admin_list_weekly_problems()
returns setof public.weekly_problems
language plpgsql
security definer set search_path = public
as $$
begin
  perform public.assert_admin();
  return query select * from public.weekly_problems order by published_at desc;
end;
$$;

create or replace function public.admin_create_weekly_problem(
  p_slug text, p_title text, p_problem_content text, p_solution_content text,
  p_topic text, p_grade_level text, p_difficulty text, p_answer_key text,
  p_published_at timestamptz, p_ends_at timestamptz, p_status text
)
returns bigint
language plpgsql
security definer set search_path = public
as $$
declare new_id bigint;
begin
  perform public.assert_admin();
  insert into public.weekly_problems (slug, title, problem_content, solution_content, topic, grade_level, difficulty, answer_key, published_at, ends_at, status, created_by)
  values (p_slug, p_title, p_problem_content, nullif(p_solution_content, ''), p_topic, p_grade_level, p_difficulty, p_answer_key, p_published_at, p_ends_at, p_status, auth.uid())
  returning id into new_id;
  return new_id;
end;
$$;

create or replace function public.admin_update_weekly_problem(
  p_id bigint, p_slug text, p_title text, p_problem_content text, p_solution_content text,
  p_topic text, p_grade_level text, p_difficulty text, p_answer_key text,
  p_published_at timestamptz, p_ends_at timestamptz, p_status text
)
returns boolean
language plpgsql
security definer set search_path = public
as $$
begin
  perform public.assert_admin();
  update public.weekly_problems set slug = p_slug, title = p_title, problem_content = p_problem_content,
    solution_content = nullif(p_solution_content, ''), topic = p_topic, grade_level = p_grade_level,
    difficulty = p_difficulty, answer_key = p_answer_key, published_at = p_published_at,
    ends_at = p_ends_at, status = p_status, updated_at = now() where id = p_id;
  return found;
end;
$$;

create or replace function public.admin_delete_weekly_problem(p_id bigint)
returns boolean
language plpgsql
security definer set search_path = public
as $$
begin
  perform public.assert_admin();
  delete from public.weekly_problems where id = p_id;
  return found;
end;
$$;

drop function if exists public.admin_list_submissions(bigint);

create function public.admin_list_submissions(p_problem_id bigint)
returns table (
  id bigint,
  problem_id bigint,
  answer_text text,
  solution_text text,
  is_correct boolean,
  has_explanation boolean,
  score integer,
  submitted_at timestamptz,
  display_name text,
  email text
)
language plpgsql
security definer set search_path = public
as $$
begin
  perform public.assert_admin();
  return query
    select
      s.id,
      s.problem_id,
      s.answer_text,
      s.solution_text,
      s.is_correct,
      s.has_explanation,
      s.score,
      s.submitted_at,
      coalesce(p.display_name, 'Matematikci') as display_name,
      u.email
    from public.submissions s
    join public.profiles p on p.id = s.user_id
    join auth.users u on u.id = s.user_id
    where s.problem_id = p_problem_id
    order by s.submitted_at desc;
end;
$$;

create or replace function public.admin_review_submission(p_problem_id bigint, p_submission_id bigint, p_is_correct boolean, p_has_explanation boolean)
returns integer
language plpgsql
security definer set search_path = public
as $$
declare awarded integer := case when p_is_correct then case when p_has_explanation then 15 else 10 end else 0 end; submission_user uuid;
begin
  perform public.assert_admin();
  update public.submissions set is_correct = p_is_correct, score = awarded where id = p_submission_id and problem_id = p_problem_id returning user_id into submission_user;
  if not found then raise exception using errcode = '22023', message = 'Submission not found'; end if;
  delete from public.score_events where submission_id = p_submission_id;
  if awarded > 0 then insert into public.score_events (user_id, submission_id, event_type, points) values (submission_user, p_submission_id, 'admin_review', awarded); end if;
  return awarded;
end;
$$;

create or replace function public.admin_highlight_submission(p_problem_id bigint, p_submission_id bigint)
returns boolean
language plpgsql
security definer set search_path = public
as $$
begin
  perform public.assert_admin();
  if not exists (select 1 from public.submissions where id = p_submission_id and problem_id = p_problem_id) then
    raise exception using errcode = '22023', message = 'Submission not found';
  end if;
  delete from public.problem_highlights where problem_id = p_problem_id;
  insert into public.problem_highlights (problem_id, submission_id, approved_by) values (p_problem_id, p_submission_id, auth.uid());
  return true;
end;
$$;

revoke all on function public.assert_admin() from public;
revoke all on function public.admin_list_weekly_problems() from public;
revoke all on function public.admin_create_weekly_problem(text, text, text, text, text, text, text, text, timestamptz, timestamptz, text) from public;
revoke all on function public.admin_update_weekly_problem(bigint, text, text, text, text, text, text, text, text, timestamptz, timestamptz, text) from public;
revoke all on function public.admin_delete_weekly_problem(bigint) from public;
revoke all on function public.admin_list_submissions(bigint) from public;
revoke all on function public.admin_review_submission(bigint, bigint, boolean, boolean) from public;
revoke all on function public.admin_highlight_submission(bigint, bigint) from public;
grant execute on function public.assert_admin() to authenticated;
grant execute on function public.admin_list_weekly_problems() to authenticated;
grant execute on function public.admin_create_weekly_problem(text, text, text, text, text, text, text, text, timestamptz, timestamptz, text) to authenticated;
grant execute on function public.admin_update_weekly_problem(bigint, text, text, text, text, text, text, text, timestamptz, timestamptz, text) to authenticated;
grant execute on function public.admin_delete_weekly_problem(bigint) to authenticated;
grant execute on function public.admin_list_submissions(bigint) to authenticated;
grant execute on function public.admin_review_submission(bigint, bigint, boolean, boolean) to authenticated;
grant execute on function public.admin_highlight_submission(bigint, bigint) to authenticated;
